version: 2
jobs:
  build:
    docker:
      - image: node:6.10.0
    working_directory: ~/youzan/zent
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: |
            yarn install && yarn bootstrap
      - run:
          name: NPM Test
          command: |
            ./scripts/check-git-hooks.sh && yarn lint && yarn test
